// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"simple-template/server/handler"
	"simple-template/server/repo"
	"simple-template/server/service"
)

// Injectors from wire.go:

func InitTodo() *handler.TodoHandler {
	todoRepo := repo.NewTodoRepo()
	todoService := service.NewTodoService(todoRepo)
	todoHandler := handler.NewTodoHandler(todoService)
	return todoHandler
}

// wire.go:

var TodoSet = wire.NewSet(repo.NewTodoRepo, service.NewTodoService, handler.NewTodoHandler)
